# ---> Site <--- #
theme: jekyll-theme-hacker
title: Cyber Bank of Information
avatar: "/assets/img/icon.png"


# ---> Author <--- #
author: gcab156
email: gcab156@protonmail.com


# ---> Footer <--- #
rss-description: By gcab156
rss: true
